# Generated by Django 5.1.7 on 2025-05-15 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_title', models.CharField(max_length=255)),
                ('issue_description', models.TextField()),
                ('priority', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Normal', 'Normal'), ('Low', 'Low')], max_length=10)),
                ('status', models.CharField(choices=[('new', 'New'), ('in-progress', 'In Progress'), ('duplicate', 'Duplicate'), ('follow-up', 'Follow Up'), ('completed', 'Completed')], default='new', max_length=20)),
                ('date_logged', models.DateTimeField(auto_now_add=True)),
                ('associated_file', models.FileField(blank=True, null=True, upload_to='issue_files/')),
                ('resolution_date', models.DateTimeField(blank=True, null=True)),
                ('work_done', models.TextField(blank=True, null=True)),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('method_of_logging', models.CharField(choices=[('gmail', 'Gmail'), ('call', 'Call')], max_length=10)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to='Staff.staff')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_issues', to='Staff.staff')),
            ],
        ),
    ]
