# Generated by Django 5.1.7 on 2025-05-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReportLog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itissue',
            name='category',
            field=models.CharField(choices=[('internet_banking', 'Internet Banking'), ('mobile_banking', 'Mobile Banking'), ('br_net', 'BR. NET'), ('network_issue', 'Network Issue'), ('hardware_issue', 'Hardware Issue'), ('others', 'Others')], default='others', max_length=30),
        ),
    ]
