# Generated by Django 5.2 on 2025-05-17 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReportLog', '0003_alter_itissue_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itissue',
            name='assigned_to',
        ),
    ]
