# services:
#   paramountbanklogsystem:
#     image: paramountbanklogsystem
#     build:
#       context: .
#       dockerfile: ./Dockerfile
#     ports:
#       - 8000:8000
version: '3.8'

services:
  paramountbanklogsystem:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn PARAMOUNT.wsgi:application --bind 0.0.0.0:8000"


  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5433"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:


