# Generated by Django 5.2 on 2025-05-22 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='branch',
            field=models.CharField(choices=[('Westlands', 'Westlands branch'), ('Parklands', 'Parklands branch'), ('Koinange', 'Koinange branch'), ('Industrial', 'Industrial area branch'), ('Kisumu', 'Kisumu branch'), ('Mombasa', 'Mombasa branch'), ('Eldoret', 'Eldoret branch'), ('Headquarters', 'Headquarters')], default='Headquarters', max_length=20),
        ),
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('User', 'User'), ('Admin', 'Admin')], default='User', max_length=10),
        ),
    ]
